# Problem-01

In [2]:
class PlayerEarning:
    def __init__(self,name):
        self.name=name
        
    def calculateTotal(self,money,match=None):
        self.money=money
        if match != None:
            if match > 30:
                self.bonus=int(((5/100)*self.money)+10000)
            else:
                self.bonus=int(((5/100)*self.money))
        else:
            self.bonus = 0
            
    def printDetails(self):
        print('Player Name:',self.name)
        print('Player Season Earning without bonus:',self.money)
        print('Bonus:',self.bonus)
        print('Player Season Earning After Bonus:',self.money+self.bonus)


print("**********************")
player1 = PlayerEarning('Buffon')
player1.calculateTotal(250000)
player1.printDetails()
print("\n**********************")
player2 = PlayerEarning('Dybala')
player2.calculateTotal(250000, 31)
player2.printDetails()
print("\n**********************")
player3 = PlayerEarning('Cuadrado')
player3.calculateTotal(250000, 20)
player3.printDetails()

**********************
Player Name: Buffon
Player Season Earning without bonus: 250000
Bonus: 0
Player Season Earning After Bonus: 250000

**********************
Player Name: Dybala
Player Season Earning without bonus: 250000
Bonus: 22500
Player Season Earning After Bonus: 272500

**********************
Player Name: Cuadrado
Player Season Earning without bonus: 250000
Bonus: 12500
Player Season Earning After Bonus: 262500

In [ ]:
**********************
Player Name: Buffon
Player Season Earning without bonus: 250000
Bonus: 0
Player Season Earning After Bonus: 250000
**********************
Player Name: Dybala
Player Season Earning without bonus: 250000
Bonus: 22500
Player Season Earning After Bonus: 272500
**********************
Player Name: Cuadrado
Player Season Earning without bonus: 250000
Bonus: 12500
Player Season Earning After Bonus: 262500
Note:

# Problem-02

In [9]:
class myList:
    sum1=0
    def __init__(self,*num):
        self.list=num
        myList.sum1=0
        self.len=len(self.list)
        
    def sum(self):
        for i in self.list:
            myList.sum1+=i
        print('Sum:',myList.sum1)
            
    def merge(self,*num1):
        self.list=num1
        self.len+=len(num1)
        
    def average(self):
        if len(self.list) == 0:
            print('Average:',0)
        else:
            print('Average:',myList.sum1/self.len)


l1 = myList(2,3,4,5,6) 
l1.sum()
l1.merge(4,5,9)
l1.sum()
l1.average()
print('-----------------------------')
l2 = myList()
l2.average()
l2.merge(1,2,4,8)
l2.sum()

Sum: 20
Sum: 38
Average: 4.75
-----------------------------
Average: 0
Sum: 15

In [ ]:
Sum: 20
Sum: 38
Average: 4.75
-----------------------------
Average: 0
Sum: 15

# Problem-03

In [25]:
class Bird:
    def __init__(self,name,fly1=False):
        self.name=name
        self.fly1=fly1
        self.ty='Flightless Birds'
        
    def fly(self):
        if self.fly1:
            print(self.name,'can fly')
        else:
            print(self.name,'can not fly')
            
    def setType(self,ty):
        self.ty=ty
        
    def printDetail(self):
        print('Name:',self.name)
        print('Tpye:',self.ty)
 
ostrich = Bird('Ostrich')
duck = Bird("Duck", True)
owl = Bird('Owl', True)
print('###########################')
ostrich.fly()
duck.fly()
owl.fly()
duck.setType('Water Birds')
owl.setType('Birds of Prey')
print('=========================')
ostrich.printDetail()
print('=========================')
duck.printDetail()
print('=========================')
owl.printDetail()

###########################
Ostrich can not fly
Duck can fly
Owl can fly
=========================
Name: Ostrich
Tpye: Flightless Birds
=========================
Name: Duck
Tpye: Water Birds
=========================
Name: Owl
Tpye: Birds of Prey

In [10]:
###########################
Ostrich can not fly
Duck can fly
Owl can fly
===========================
Name: Ostrich
Type: Flightless Birds
===========================
Name: Duck
Type: Water Birds

SyntaxError: invalid syntax (<ipython-input-10-190aa9fbf7c8>, line 2)

# Problem-04

In [31]:
class Account:
    count=0
    def __init__(self,name,age,pro,amount):
        self.name=name
        self.age=age
        self.pro=pro
        self.amount=amount
        Account.count+=1
        
    def addMoney(self,acc):
        self.amount+=acc
    
    def withdrawMoney(self,acc):
        if str(self.amount)[0] == '-':
            self.amount=0
        elif self.amount >= acc:
            self.amount-=acc
        else:
            self.amount=self.amount
        
    def printDetails(self):
        print('Name:',self.name)
        print('Age:',self.age)
        print('Occupation:',self.pro)
        print('Total Amount:',self.amount)

print('No of account holders:', Account.count)
print("=========================")
p1 = Account("Abdul", 45, "Service Holder", 500000)
p1.addMoney(300000)
p1.printDetails()
print("=========================")
p2 = Account("Rahim", 55, "Businessman", 700000)
p2.withdrawMoney(700000)
p2.printDetails()
print("=========================")
p3 = Account("Ashraf", 62, "Govt. Officer", 200000)
p3.withdrawMoney(250000)
p3.printDetails()
print("=========================")
print('No of account holders:', Account.count)

No of account holders: 0
=========================
Name: Abdul
Age: 45
Occupation: Service Holder
Total Amount: 800000
=========================
Name: Rahim
Age: 55
Occupation: Businessman
Total Amount: 0
=========================
Name: Ashraf
Age: 62
Occupation: Govt. Officer
Total Amount: 200000
=========================
No of account holders: 3

In [ ]:
No of account holders: 0
=========================
Name: Abdul
Age: 45
Occupation: Service Holder
Total Amount: 800000
=========================
Name: Rahim
Age: 55
Occupation: Businessman
Total Amount: 0
=========================
Name: Ashraf
Age: 62
Occupation: Govt. Officer
Total Amount: 200000
=========================
No of account holders: 3

# Problem-05

In [36]:
class Smartphone:
    def __init__(self,name=None):
        self.dict={}
        self.name=name
        pass
    def addFeature(self,*other):
        if self.name == None:
            print('Feature can not be added without phone name')
        else:
            if other[0] not in self.dict:
                self.dict[other[0]]=[other[1]]
            else:
                self.dict[other[0]].append(other[1])
                
    def setName(self,name):
        self.name=name
        
    def printDetail(self):
        print('Phone name:',self.name)
        for i,k in self.dict.items():
            print(i,':',k)

s1 = Smartphone()
print("=================================")
s1.addFeature('Display', '6.1 inch')
print("=================================")
s1.setName('Samsung Note 20')
s1.addFeature('Display', '6.1 inch')
s1.printDetail()
print("=================================")
s2 = Smartphone('Iphone 12 Pro')
s2.addFeature('Display', '6.2 inch')
s2.addFeature('Ram', '6 GB')
print('=================================')
s2.printDetail()
s2.addFeature('Display', 'Amoled panel')
s2.addFeature('Ram', 'DDR5')
print("=================================")
s2.printDetail()
print("=================================")

=================================
Feature can not be added without phone name
=================================
Phone name: Samsung Note 20
Display : ['6.1 inch']
=================================
=================================
Phone name: Iphone 12 Pro
Display : ['6.2 inch']
Ram : ['6 GB']
=================================
Phone name: Iphone 12 Pro
Display : ['6.2 inch', 'Amoled panel']
Ram : ['6 GB', 'DDR5']
=================================

In [ ]:
=================================
Feature can not be added without phone name
=================================
Phone Name: Samsung Note 20
Display: 6.1 inch
=================================
=================================
Phone Name: Iphone 12 Pro
Display: 6.2 inch
Ram: 6 GB
=================================
Phone Name: Iphone 12 Pro
Display: 6.2 inch, Amoled panel
Ram: 6 GB, DDR5
=================================

# Problem-06

In [38]:
class Student:
    count_cse=0
    count_bba=0
    count=0
    def __init__(self,name,dep):
        self.name=name
        self.dep=dep
        Student.count+=1
        print('Creating Student Number:',Student.count)
        if self.dep == 'CSE':
            Student.count_cse+=1
        if self.dep == 'BBA':
            Student.count_bba+=1
        
    def individualInfo(self):
        print(self.name,'is from CSE',self.dep,'department.')
        print("Serial of Naruto among all students' is:",Student.count)
        if self.dep == 'CSE':
            print('Serial of Naruto in CSE department is:',Student.count_cse)
        if self.dep == 'BBA':
            print('Serial of Naruto in BBA department is:',Student.count_bba)
        
    def totalInfo(self):
        print('Total Number of Student:',Student.count)
        print('Total Number of CSE Student:',Student.count_cse)
        print('Total Number of BBA Student:',Student.count_bba)
        
        
s1 = Student("Naruto", "CSE")
print('----------------------')
s1.individualInfo()
print('#############################')
s1.totalInfo()
print('============================')
s2 = Student("Sakura", "BBA")
print('----------------------')
s2.individualInfo()
print('#############################')
s2.totalInfo()
print('============================')
s3 = Student("Shikamaru", "CSE")
print('----------------------')
s3.individualInfo()
print('#############################')
s3.totalInfo()
print('============================')
s4 = Student("Deidara", "BBA")
print('----------------------')
s4.individualInfo()
print('#############################')
s4.totalInfo()

Creating Student Number: 1
----------------------
Naruto is from CSE CSE department.
Serial of Naruto among all students' is: 1
Serial of Naruto in CSE department is: 1
#############################
Total Number of Student: 1
Total Number of CSE Student: 1
Total Number of BBA Student: 0
============================
Creating Student Number: 2
----------------------
Sakura is from CSE BBA department.
Serial of Naruto among all students' is: 2
Serial of Naruto in BBA department is: 1
#############################
Total Number of Student: 2
Total Number of CSE Student: 1
Total Number of BBA Student: 1
============================
Creating Student Number: 3
----------------------
Shikamaru is from CSE CSE department.
Serial of Naruto among all students' is: 3
Serial of Naruto in CSE department is: 2
#############################
Total Number of Student: 3
Total Number of CSE Student: 2
Total Number of BBA Student: 1
============================
Creating Student Number: 4
----------------------
Deidara is from CSE BBA department.
Serial of Naruto among all students' is: 4
Serial of Naruto in BBA department is: 2
#############################
Total Number of Student: 4
Total Number of CSE Student: 2
Total Number of BBA Student: 2

In [ ]:
Creating Student Number: 1
----------------------
Naruto is from CSE department.
Serial of Naruto among all students' is: 1
Serial of Naruto in CSE department is: 1
#############################
Total Number of Student: 1
Total Number of CSE Student: 1
Total Number of BBA Student: 0
============================
Creating Student Number: 2
----------------------
Sakura is from BBA department.
Serial of Sakura among all students' is: 2
Serial of Sakura in BBA department is: 1
#############################
Total Number of Student: 2
Total Number of CSE Student: 1
Total Number of BBA Student: 1
============================
Creating Student Number: 3
----------------------
Shikamaru is from CSE department.
Serial of Shikamaru among all students' is: 3
Serial of Shikamaru in CSE department is: 2
#############################
Total Number of Student: 3
Total Number of CSE Student: 2
Total Number of BBA Student: 1
============================
Creating Student Number: 4
----------------------
Deidara is from BBA department.
Serial of Deidara among all students' is: 4
Serial of Deidara in BBA department is: 2
#############################
Total Number of Student: 4
Total Number of CSE Student: 2
Total Number of BBA Student: 2

# Problem-07

In [6]:
class book:
    def __init__(self, name):
        self.name = name
        self.genre='biography'
    def review(self):
        print('This book is just out of the world,mind-blowing!')
        
class fiction(book):
    def __init__(self,name,cata):
        super().__init__(name)
        self.catagory=cata
        
    def review(self):
        print(self.name,'which is a',self.catagory,'is just out of the world, mind-blowing!')
        
class nonfiction(book):
    def __init__(self,name,cata='biography'):
        super().__init__(name)
        self.catagory=cata
        
    def review(self):
        print(self.name,'which is a',self.catagory,'is just out of the world, mind-blowing!')
    
b1 = fiction('The Shining','Psychological horror')
b2 = nonfiction('A Beautiful Mind')
b1.review()
print('=========================')
b2.review()
print('=========================')

The Shining which is a Psychological horror is just out of the world, mind-blowing!
=========================
A Beautiful Mind which is a biography is just out of the world, mind-blowing!
=========================

In [ ]:
The Shining which is a Psychological horror is just out of the world, mind-blowing!
=========================
A Beautiful Mind which is a biography is just out of the world, mind-blowing!
=========================

# Problem-08

In [10]:
class Processor:
    def __init__(self, model, thread, core):
        self.model = model
        self.core = core
        self.thread = thread
    def getInfo(self):
        return 'Model:'+self.model+ '\nCores:'+str(self.core)+ '\nThreads:'+ str(self.thread)
    
class Intel(Processor):
    def __init__(self,model,core,thread,price):
        super().__init__(model,thread,core)
        self.price=price
    
    def getInfo(self):
        print(super().getInfo()+'\n'+'Price: '+str(self.price))
        
class AMD(Processor):
    def __init__(self,model,core,thread,price):
        super().__init__(model,thread,core)
        self.price=price
    
    def getInfo(self):
        print(super().getInfo()+'\n'+'Price: '+str(self.price))
      
p1 = Intel("Intel i5 10th Gen",6,12,17000)
p2 = AMD("Ryzen 5 3500X",6,6,13800)
p3 = AMD("Ryzen 5 3600",6,12,16900)
print('======================')
p1.getInfo()
print('======================')
p2.getInfo()
print('======================')
p3.getInfo()

======================
Model:Intel i5 10th Gen
Cores:6
Threads:12
Price: 17000
======================
Model:Ryzen 5 3500X
Cores:6
Threads:6
Price: 13800
======================
Model:Ryzen 5 3600
Cores:6
Threads:12
Price: 16900

In [ ]:
======================
Model: Intel i5 10th Gen
Cores: 6
Threads: 12
Price: 17000 taka
======================
Model: Ryzen 5 3500X
Cores: 6
Threads: 6
Price: 13800 taka
======================
Model: Ryzen 5 3600
Cores: 6
Threads: 12
Price: 16900 taka

# Problem-09

In [19]:
class Fruit:
    Total_order=0
    def __init__(self, Order_ID, weight):
        self.Order_ID=Order_ID
        self.weight=weight
        Fruit.Total_order=Fruit.Total_order+1
    def __str__(self):
        return self.Order_ID+", Weight: "+str(self.weight)
    
class Mango(Fruit):
    def __init__(self,order,weight,var,price):
        super().__init__(order,weight)
        self.veriable=var
        self.price=price*weight
        
    def __str__(self):
        return super().__str__()+', Variety: '+self.veriable+'\nTotal Price: '+str(self.price)
        
    def __add__(self,other):
        x = self.price+other.price
        return 'The total Price of the orders are: '+str(x)
        
class JackFruit(Fruit):
    def __init__(self,order,weight,price):
        super().__init__(order,weight)
        self.price=price*weight
        
    def __str__(self):
        return super().__str__()+', Total Price: '+str(self.price)
    
    def __add__(self,other):
        x = self.price+other.price
        return 'The total Price of the orders are: '+str(x)

    
m1=Mango("Order Id 1", 5,"GopalVog",250)
print(m1)
m2=Mango("Order Id 2", 5,"HariVanga", 230)
print(m2)
j1=JackFruit("Order Id 3", 5,250)
print(j1)
j2=JackFruit("Order Id 4", 4,210)
print(j2)
print("Total number of Orders: "+str(Fruit.Total_order))
print("==================")
print(m1+m2)
print("==================")
print(j1+j2)

Order Id 1, Weight: 5, Variety: GopalVog
Total Price: 1250
Order Id 2, Weight: 5, Variety: HariVanga
Total Price: 1150
Order Id 3, Weight: 5, Total Price: 1250
Order Id 4, Weight: 4, Total Price: 840
Total number of Orders: 4
==================
The total Price of the orders are: 2400
==================
The total Price of the orders are: 2090

In [ ]:
Order Id 1, Weight: 5, Variety: GopalVog,
Total Price: 1250
Order Id 2, Weight: 5, Variety: HariVanga,
Total Price: 1150
Order Id 3, Weight: 5, Total Price: 1250
Order Id 4, Weight: 4, Total Price: 840
Total number of Orders: 4
==================
The total Price of the orders are: 2400
==================
The total Price of the orders are: 2090

# Problem-10

In [24]:
class Student:
    def __init__(self,name,ID):
        self.name = name
        self.ID = ID
    def Details(self):
        return "Name: "+self.name+"\n"+"ID: "+self.ID+"\n"
    
class CSEStudent(Student):
    def __init__(self,name,id1,semester):
        super().__init__(name,id1)
        self.semester=semester
    def Details(self):
        return super().Details()+'Current semester: '+self.semester
    
    def addCourseWithMarks(self,*marks):
        self.list_course=[]
        self.list_mark=[]
        for i in range(0,len(marks)):
            if i%2 ==0:
                self.list_course.append(marks[i])
            else:
                if marks[i] >= 0 and marks[i] <= 50:
                    self.list_mark.append(0.00)
                elif marks[i] >= 51 and marks[i] <= 54:
                    self.list_mark.append(1.00)
                elif marks[i] >= 55 and marks[i] <= 56:
                    self.list_mark.append(1.33)
                elif marks[i] >= 57 and marks[i] <= 64:
                    self.list_mark.append(2.00)
                elif marks[i] >= 65 and marks[i] <= 69:
                    self.list_mark.append(2.3)
                elif marks[i] >= 70 and marks[i] <= 79:
                    self.list_mark.append(3.00)
                elif marks[i] >= 80 and marks[i] <= 84:
                    self.list_mark.append(3.3)
                else:
                    self.list_mark.append(4.00)
                       
    def showGPA(self):
        print(self.name,'has taken',len(self.list_course),'courses.')
        sum1=0
        for i in range(0,len(self.list_course)):
            sum1+=self.list_mark[i]*3
            print(self.list_course[i],':',self.list_mark[i])
            
        print('GPA of',self.name,'is',sum1/(len(self.list_course)*3))

Bob = CSEStudent("Bob","20301018",'Fall 2020')
Carol = CSEStudent("Carol","16301814",'Fall 2020')
Anny = CSEStudent("Anny","18201234",'Fall 2020')
print("#########################")
print(Bob.Details())
print("#########################")
print(Carol.Details())
print("#########################")
print(Anny.Details())
print("#########################")
Bob.addCourseWithMarks("CSE111",83.5,"CSE230",73.0,"CSE260",92.5)
Carol.addCourseWithMarks("CSE470",62.5,"CSE422",69.0,"CSE460",76.5,"CSE461",87.0)
Anny.addCourseWithMarks("CSE340",45.5,"CSE321",95.0,"CSE370",91.0)
print("----------------------------")
Bob.showGPA()
print("----------------------------")
Carol.showGPA()
print("----------------------------")
Anny.showGPA()

#########################
Name: Bob
ID: 20301018
Current semester: Fall 2020
#########################
Name: Carol
ID: 16301814
Current semester: Fall 2020
#########################
Name: Anny
ID: 18201234
Current semester: Fall 2020
#########################
----------------------------
Bob has taken 3 courses.
CSE111 : 3.3
CSE230 : 3.0
CSE260 : 4.0
GPA of Bob is 3.433333333333333
----------------------------
Carol has taken 4 courses.
CSE470 : 2.0
CSE422 : 2.3
CSE460 : 3.0
CSE461 : 4.0
GPA of Carol is 2.8249999999999997
----------------------------
Anny has taken 3 courses.
CSE340 : 0.0
CSE321 : 4.0
CSE370 : 4.0
GPA of Anny is 2.6666666666666665

In [ ]:
#########################
Name: Bob
ID: 20301018
Current semester: Fall 2020
#########################
Name: Carol
ID: 16301814
Current semester: Fall 2020
#########################
Name: Anny
ID: 18201234
Current semester: Fall 2020
#########################
----------------------------
Bob has taken 3 courses.
CSE111: 3.3
CSE230: 3.0
CSE260: 4.0
GPA of Bob is: 3.43
----------------------------
Carol has taken 4 courses.
CSE470: 2.0
CSE422: 2.3
CSE460: 3.0
CSE461: 4.0
GPA of Carol is: 2.83
----------------------------
Anny has taken 3 courses.
CSE340: 0.0
CSE321: 4.0
CSE370: 4.0
GPA of Anny is: 2.67

# Problem-11

In [1]:
class Transport:
    total_traveller = 0
    def __init__(self, name, fare):
        self.name = name
        self.baseFare = fare
    def __str__(self):
        s = 'Name: '+self.name+", Base fare: "+str(self.baseFare)
        return s
    
class Bus(Transport):
    def __init__(self,name,price):
        super().__init__(name,price)
        print(super().__str__())
        self.count1=0
        
    def addPassengerWithBags(self,*other):
        self.list1=[]
        self.list2=[]
        
        for i in range(0,len(other)):
            if i%2==0:
                self.list1.append(other[i])
            else:
                if other[i] <= 2:
                    self.list2.append(self.baseFare)
                elif other[i] >= 3 and other[i] <= 5:
                    self.list2.append(self.baseFare+60)
                else:
                    self.list2.append(self.baseFare+105)
                
        Transport.total_traveller+=len(self.list1)
        self.count1+=len(self.list1)
        
    def __str__(self):
        sum1=''
        for i in range(0,len(self.list1)):
            sum1+='Name: '+self.list1[i]+', Fare: '+str(self.list2[i])+'\n'
            
        return super().__str__()+'\nTotal Passenger(s): '+str(self.count1)+'\nPassenger details:\n' +sum1
    
class Train(Transport):
    def __init__(self,name,price):
        super().__init__(name,price)
        print(super().__str__())
        self.count1=0
        
    def addPassengerWithBags(self,*other):
        self.list1=[]
        self.list2=[]
        
        for i in range(0,len(other)):
            if i%2==0:
                self.list1.append(other[i])
            else:
                if other[i] <= 2:
                    self.list2.append(self.baseFare)
                elif other[i] >= 3 and other[i] <= 5:
                    self.list2.append(self.baseFare+60)
                else:
                    self.list2.append(self.baseFare+105)
                       
        Transport.total_traveller+=len(self.list1)
        self.count1+=len(self.list1)
        
    def __str__(self):
        sum1=''
        for i in range(0,len(self.list1)):
            sum1+='Name: '+self.list1[i]+', Fare: '+str(self.list2[i])+'\n'
            
        return super().__str__()+'\nTotal Passenger(s): '+str(self.count1)+'\nPassenger details:\n'+sum1

t1 = Bus('Volvo', 950)
print("=================================")
t1.addPassengerWithBags('David', 6, 'Mike', 1, 'Carol', 3)
print("=================================")
print(t1)
print("=================================")
t2 = Train('Silk City', 850)
print("=================================")
t2.addPassengerWithBags('Bob', 2, 'Simon', 4)
print("=================================")
print(t2)
print("=================================")
print('Total Passengers in Transport: ',Transport.total_traveller )

Name: Volvo, Base fare: 950
=================================
=================================
Name: Volvo, Base fare: 950
Total Passenger(s): 3
Passenger details:
Name: David, Fare: 1055
Name: Mike, Fare: 950
Name: Carol, Fare: 1010

=================================
Name: Silk City, Base fare: 850
=================================
=================================
Name: Silk City, Base fare: 850
Total Passenger(s): 2
Passenger details:
Name: Bob, Fare: 850
Name: Simon, Fare: 910

=================================
Total Passengers in Transport:  5

In [ ]:
Base-fare of Volvo is 950 Taka
===============================
===============================
Name: Volvo, Base fare: 950
Total Passenger(s): 3
Passenger details:
Name: David, Fare: 1055
Name: Mike, Fare: 950
Name: Carol, Fare: 1010
===============================
Base-fare of Silk City is 850 Taka
===============================
===============================
Name: Silk City, Base fare: 850
Total Passenger(s): 2
Passenger details:
Name: Bob, Fare: 850
Name: Simon, Fare: 910
===============================
Total Passengers in Transport: 5

# Problem-12

In [14]:
class AppleProduct:
    def __init__(self, name, model,base_price):
        self.name = name
        self.model = model
        self.base_price = base_price
    def companyInfo(self):
        st = ("Company Name: Apple\nFouder: Steve Jobs, Steve Wozniak, Ronald Wayne\nCurrent CEO: Tim Cook\nAddress: Apple Inc, 2511Laguna Blvd, Elk Grove, CA 95758, UnitedStates")
        return st
    def feature(self):
        st = (f"Name: {self.name}\nProduct Model: {self.model}\nHardware Quality: Excellent Hardwares\nGuarantee/ Warranty: Apple Care")
        return st
    def __str__(self):
        print('This is apple product.')
    def calculatePrice(self):
        print('Total Price:', self.base_price)

class MacBookPro2020(AppleProduct):
    def __init__(self,name,model,ram,chip,tax,price=1299):
        super().__init__(name,model,price)
        self.ram=ram
        self.chip=chip
        self.tax=tax
        
    def __str__(self):
        return 'Product Details:\n'+super().feature()+'\n'+super().companyInfo()
        
    def calculatePrice(self):
        print('Calculating Total Price:')
        print('Base Price:',self.base_price)
        print('Tax:',self.tax)
        self.base_price+=(self.base_price*self.tax)/100
        super().calculatePrice()
        
    def __add__(self,other):
        sum1=self.base_price+other.base_price
        return sum1
        
class iPhone12(AppleProduct):
    def __init__(self,name,model,ram,chip,tax,price=799):
        super().__init__(name,model,price)
        self.ram=ram
        self.chip=chip
        self.tax=tax
        
    def __str__(self):
        return 'Product Details:\n'+super().feature()+'\n'+super().companyInfo()
        
    def calculatePrice(self):
        print('Calculating Total Price:')
        print('Base Price:',self.base_price)
        print('Tax:',self.tax)
        self.base_price+=(self.base_price*self.tax)/100
        super().calculatePrice()
        
            
m1 = MacBookPro2020('MacBook','MacBookPro2020', 8, 'M1', 10)
print(m1)
print('====================================')
m1.calculatePrice()
print('###################################')
iphone = iPhone12('iPhone', 'iPhone 12', 8,'A14', 5)
print(iphone)
print('====================================')
iphone.calculatePrice()
print('###################################')
print('Total Price of these two products:',end='')
print('%.2f Dollars '%(m1 + iphone))

Product Details:
Name: MacBook
Product Model: MacBookPro2020
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511Laguna Blvd, Elk Grove, CA 95758, UnitedStates
====================================
Calculating Total Price:
Base Price: 1299
Tax: 10
Total Price: 1428.9
###################################
Product Details:
Name: iPhone
Product Model: iPhone 12
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511Laguna Blvd, Elk Grove, CA 95758, UnitedStates
====================================
Calculating Total Price:
Base Price: 799
Tax: 5
Total Price: 838.95
###################################
Total Price of these two products:2267.85 Dollars

In [ ]:
Product Details:
Name: MacBook
Product Model: MacBookPro2020
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
RAM: 8GB
Chip: M1
Company Details:
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
====================================
Calculating Total Price:
Base Price: 1299
Tax: 10%
Total Price: 1428.9
###################################
Product Details:
Name: iPhone
Product Model: iPhone 12
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
RAM: 8GB
Chip: A14
Company Details:
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
====================================
Calculating Total Price:
Base Price: 799
Tax: 5%
Total Price: 838.95
###################################
Total Price of these two products: 2267.85 Dollars

# Problem-13

In [2]:
class University:
    name = "ABC University"
    numberOfStudents = 0
    admissionFee = 28000
    Library = 2000
    def __init__(self, n,i):
        self.stName = n
        self.stId = i
    def payment(self):
        return self.admissionFee + self.Library
    def __str__(self):
        return "Student Name: {}, ID: {}\nFee: {}".format(self.stName, self.stId, self.payment())

class CSE_dept(University):
    PerCreditFee=6600
    def __init__(self,name,id1,credit=6):
        super().__init__(name,id1)
        self.credit=credit
        
    def payment(self):
        return self.admissionFee+ self.Library+ (self.credit*CSE_dept.PerCredit)+ 2750+7700
        
    def __str__(self):
        if CSE_dept.PerCreditFee == 6600:
            str1='DETAILS:\nAdmission Fee: '+str(University.admissionFee)+'\nLibrary Fee: '+str(University.Library)+'\nSemester Fee: 7700\nPer Credit Fee: '+str(self.credit)
            return super().__str__()+'\n'+str1+'\nPer Credit Fee: 6600\nLab Fee: 2750'
        else:
            return super().__str__()
    
c1 = CSE_dept("Mary","5678")
print(c1)
c1.payment_details()
print("===========================")
p1 = PHR_dept("Simon","91011")
print(p1)
p1.payment_details()
print("===========================")
c2 = CSE_dept("Adam","1234", 12)
print(c2)
c2.payment_details()
print("===========================")
p2 = PHR_dept("David","121314", 15)
print(p2)
p2.payment_details()
print("===========================")
print("Total Number of Students:",University.numberOfStudents)
print("Total University Revenue:", (c1 + c2) + (p1 + p2))
print("===========================")
print("Due to the pandemic, admission and library fees have been reduced for all departments. ")
University.admissionFee -= 1000
University.Library -= 100
print("The credit, semester and lab fees have been reduced for the CSE department. ")
CSE_dept.PerCreditFee -= 100
CSE_dept.SemesterFee -= 100
CSE_dept.LabFee -=100
print("The credit and semester fees have been reduced for the PHR department.\n ")
PHR_dept.PerCreditFee -= 100
PHR_dept.SemesterFee -= 1000
print(c1)
print(p1)
print(c2)
print(p2)
print("===========================")
print("Total Number of Students:",University.numberOfStudents)
print("Total University Revenue:",(c1 + c2) + (p1 + p2))

AttributeError: type object 'CSE_dept' has no attribute 'PerCredit'

In [ ]:
Student Name: Mary, ID: 5678
Fee: 80050
DETAILS:
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 7700
Per Credit Fee: 6600
Number of credits: 6
Lab Fee: 2750
===========================
Student Name: Simon, ID: 91011
Fee: 100400
DETAILS:
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 11000
Per Credit Fee: 6600
Number of credits: 9
===========================
Student Name: Adam, ID: 1234
Fee: 119650
DETAILS:
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 7700
Per Credit Fee: 6600
Number of credits: 12
Lab Fee: 2750
===========================
Student Name: David, ID: 121314
Fee: 140000
DETAILS:
Admission Fee: 28000
Library Fee: 2000
Semester Fee: 11000
Per Credit Fee: 6600
Number of credits: 15
===========================
Total Number of Students: 4
Total University Revenue: 440100
===========================
Due to the pandemic, admission and library fees have been reduced for all departments.
The credit, semester and lab fees have been reduced for the CSE department.
The credit and semester fees have been reduced for the PHR department.
Student Name: Mary, ID: 5678
Fee: 78150
Student Name: Simon, ID: 91011
Fee: 97400
Student Name: Adam, ID: 1234
Fee: 117150
Student Name: David, ID: 121314
Fee: 136400
===========================
Total Number of Students: 4
Total University Revenue: 429100

# Problem-14

# Problem-15

In [8]:
class Player:
    database={}
    playerNo = 0
    def __init__(self,name,team,jerseyNo):
        self.name = name
        self.team = team
        self.jerseyNo = jerseyNo
    def __str__(self):
        return "Name:{}\nTeam:{}\nJersey No:{}".format(self.name,self.team,self.jerseyNo)

class FootballPlayer(Player):
    def __init__(self,name,tname,jersey,goal,date='Not yet retired'):
        super().__init__(name,tname,jersey)
        self.goal=goal
        self.date=date
        Player.playerNo+=1
        
    def __str__(self):
        str1=''
        for i in self.name.split():
            str1+=i[0]
        return 'Player ID: '+str(Player.playerNo)+str1+str(self.jerseyNo)+'\n'+super().__str__()+'\nGoals Scored: '+str(self.goal)+'\nRetirement date:'+str(self.date)
        Player.database[str1]=[self.name,self.team,self.jerseyNo,self.goal,self.date]
        
    @classmethod
    def createPlayer(cls,name,tname,jersey,goal,date):
        return FootballPlayer(name,tname,jersey,goal,date)
    
print("Number of players:",Player.playerNo)
print("Player Database:",Player.database)
print("#################################")
p1 = FootballPlayer("Lionel Messi","Barcelona",10,231)
print("------Details of the player------")
print(p1)
print("#################################")
p2 = FootballPlayer("Cristiano Ronaldo","Juventus",7,215)
print("------Details of the player------")
print(p2)
print("#################################")
p3 = FootballPlayer.createPlayer("Miroslav Klose","Lazio",11,71,"11 Aug,2014")
print("------Details of the player------")
print(p3)
print("#################################")
print("Number of players:",Player.playerNo)
print("Player Database:",Player.database)

Number of players: 0
Player Database: {}
#################################
------Details of the player------
Player ID: 1LM10
Name:Lionel Messi
Team:Barcelona
Jersey No:10
Goals Scored: 231
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID: 2CR7
Name:Cristiano Ronaldo
Team:Juventus
Jersey No:7
Goals Scored: 215
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID: 3MK11
Name:Miroslav Klose
Team:Lazio
Jersey No:11
Goals Scored: 71
Retirement date:11 Aug,2014
#################################
Number of players: 3
Player Database: {}

In [ ]:
Number of players: 0
Player Database: {}
#################################
------Details of the player------
Player ID:1LM10
Name:Lionel Messi
Team:Barcelona
Jersey No:10
Goals Scored:231
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID:2CR7
Name:Cristiano Ronaldo
Team:Juventus
Jersey No:7
Goals Scored:215
Retirement date:Not yet retired
#################################
------Details of the player------
Player ID:3MK11
Name:Miroslav Klose
Team:Lazio
Jersey No:11
Goals Scored:71
Retirement date:11 Aug,2014
#################################
Number of players: 3
Player Database: {'1LM10': ['Lionel Messi',
'Barcelona', 10, 231, 'Not yet retired'], '2CR7':
['Cristiano Ronaldo', 'Juventus', 7, 215, 'Not yet
retired'], '3MK11': ['Miroslav Klose', 'Lazio', 11,
71, '11 Aug,2014']}